deployment:
  tasks:
    - export DEPLOYPATH=/home/wozacok1/gittest.woza.co.ke/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -r assets/ $DEPLOYPATH